# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: github-action-release-branch-manager
  description: Easily Manage Release Branches for Long Term Support (LTS)
  homepage: https://cloudposse.com/accelerate
  topics: ""

