name: 'Release Branch Manager GitHub Action'
description: 'Creates release branch based on tag major version'
author: hello@cloudposse.com
branding:
  icon: 'file'
  color: 'white'
inputs:
  log-level:
    description: "Log level for this action. Available options: ['off', 'error', 'warn', 'info', 'debug']. Default 'info'"
    required: false
    default: "info"
outputs:
  response:
    description: 'Response in json format for example: {"succeeded":true,"reason":"CREATED_BRANCHES","message":"Successfully created release branches","data":{"release/v3":"3.1.0","release/v2":"2.0.0","release/v1":"1.1.0"}}'
    value: ${{ steps.run_release_branch_manager.outputs.response }}
runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Node Dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}
        npm install

    - name: Run Release Branch Manager
      shell: bash
      id: run_release_branch_manager
      run: |
        cd ${{ github.action_path }}
        export LOG_LEVEL='${{ inputs.log-level }}'
        node index.js $GITHUB_WORKSPACE

    - name: Get the output
      shell: bash
      run: |
        echo "${{ steps.run_release_branch_manager.outputs.response }}"
