name: 'Releaser GitHub Action'
description: 'Creates release branch based on tag major version'
author: hello@cloudposse.com
branding:
  icon: 'file'
  color: 'white'
inputs:
  log-level:
    description: "Log level for this action. Default 'INFO'"
    required: false
    default: 'INFO'
runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python Dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}
        pip install -r requirements.txt

    - name: Run Releaser
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      shell: bash
      run: |
        cd ${{ github.action_path }}
        escaped_github_context=$(printf "%q" $GITHUB_CONTEXT)
        echo "======================="
        echo $escaped_github_context
        echo "======================="
        python main.py \
          --github-context $escaped_github_context \
          --log-level ${{ inputs.log-level }}
