name: 'Releaser GitHub Action'
description: 'Creates release branch based on tag major version'
author: hello@cloudposse.com
branding:
  icon: 'file'
  color: 'white'
inputs:
  log-level:
    description: "Log level for this action. Default 'INFO'"
    required: false
    default: 'INFO'
runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Run Release Branch Manager
      shell: bash
      run: |
        node ./index.js
